10 DEFINT A:INPUT K:DIM A(K):DATA 2,1,4,7,8
30 FOR I=1 TO K:READ A(I):NEXTI:GOSUB 100:END
100 FOR J=1 TO K:IF VAL(RIGHT$(STR$(A(J)),1))MOD2=1THENPRINTA(J):RETURN ELSE NEXTJ 
120 PRINT "нечетных элементов в массиве нет":RETURN
