5 CLEAR:INPUT A$:A$=A$+"":A=PEEK(VARPTR(A$)):PRINT A
30 B$="&H"+HEX$(PEEK(VARPTR(A$)+2))+HEX$(PEEK(VARPTR(A$)+1)):PRINT B$
40 B=VAL(B$):BB=PEEK(B)
45 FOR I=0 TO A-1:PRINT CHR$(PEEK(B+I));:NEXT I:END
