1 PRINT HEX$(PEEK(&HF69C)); HEX$(PEEK(&HF69B));
2 A$="ABCD"+"EF"
3 FOR T=0 TO 5:PRINT CHR$(PEEK(&HF168-T));:NEXT
4 A$="X"+"Y"
5 FOR T=0 TO 7:PRINT CHR$(PEEK(&HF168-T));:NEXT
6 PRINT FRE("")'Избавимся от "мусора"!
7 FOR T=0 TO 7:PRINT CHR$(PEEK(&HF168-T));:NEXT
