10 LPRINT CHR$(14);"EXPANDED PICA PITCH"
20 LPRINT CHR$(27);"E":LPRINT "EXPANDED ELITE PITCH"
40 LPRINT CHR$(27);"Q":LPRINT "EXPANDED CONDENSED PITCH"
60 LPRINT CHR$(27);"P";CHR$(15)
70 LPRINT "NOW WE ARE BACK TO UNEXPANDED PICA PRINTING"
