10 LPRINT CHR$(27);"N":LPRINT "WHAT IS YOUR NAME?"
30 LPRINT CHR$(27);"E":LPRINT "YOUR PRINTER PRINTS IN ELITE PITCH"
50 LPRINT CHR$(27);"Q":LPRINT "AS WELL AS CONDENSED, THE NARROOWEST PITCH"
70 LPRINT CHR$(27);"R"
80 LPRINT "PICA PITCH PRINTING IS PRINTER'S THIRD PITCH"
