10 LPRINT "LINE NUMBER 1.":LPRINT "LINE NUMBER 2.";
30 LPRINT CHR$(12);
40 LPRINT "LINE NUMBER 3.":LPRINT "LINE NUMBER 4."
50 LPRINT CHR$(11);
60 LPRINT "LINE NUMBER 5.":LPRINT "LINE NUMBER 6."
