10 DEFINT N,I,J:INPUT N:DIM X(N):Z=RND(-TIME)
30 FOR I=1 TO N:X(I)=INT(3*RND(1)):PRINTX(I);:NEXTI
40 FOR I=1 TO N-1:FOR J=I+1 TO N
50 IF X(I)<X(J) THEN GOTO 60 ELSE SWAP X(I),X(J)
60 NEXT:NEXT:PRINT
70 FOR I=1 TO N:PRINT X(I);:NEXT
