10 INPUT M
20 N$=STR$(M)
30 FOR I=2 TO LEN(N$)-1
40 FOR J=I+1 TO LEN(N$)
50 IF MID$(N$,I,1)=MID$(N$,J,1) THEN IF VAL(MID$(N$,I,1))>A THEN A=VAL(MID$(N$,I,1)):NEXTI ELSE ELSE NEXTJ:NEXTI
60 PRINT A
