10 DEFINT I,J,M:DEFSTR A:INPUT M
30 FOR I=1 TO M:A=STR$(I):FOR J=2 TO LEN(A)
55 IF VAL(MID$(A,J,1))=0 THEN NEXT J:NEXT I:END ELSE::::IF I MOD VAL(MID$(A,J,1))=0 THEN NEXTJ:PRINTI;:NEXTI ELSE NEXTI
