10 INPUT"Введите число элементов в массиве A, затем - в массиве B";N,M:FF=RND(-TIME)
20 DIM A(N),B(M),C(N+M)
30 FOR K=1 TO N:A(K)=INT(7*RND(1)):NEXT
40 FOR L=1 TO M:B(L)=INT(9*RND(1)):NEXT
41 FOR I=1 TO N-1:FOR J=I+1 TO N:IF A(I)>A(J) THEN SWAP A(I),A(J)
42 NEXT J,I
43 FOR I=1 TO N:PRINT A(I);:NEXT:PRINT
45 FOR I=1 TO M-1:FOR J=I+1 TO M:IF B(I)>B(J) THEN SWAP B(I),B(J)
46 NEXT J,I
47 FOR I=1 TO M:PRINT B(I);:NEXT:PRINT
50 P=0:Q=0
60 FOR I=1 TO N+M
70 IF P=N THEN Q=Q+1:C(I)=B(Q):NEXT:GOTO 110
80 IF Q=M THEN P=P+1:C(I)=A(P):NEXT:GOTO 110
90 IF A(P+1)<B(Q+1) THEN P=P+1:C(I)=A(P) ELSE Q=Q+1:C(I)=B(Q)
100 NEXT
110 FOR I=1 TO N+M:PRINT C(I);:NEXT
