10 INPUT"õËÁÖÉÔÅ N É K";N,K:IF K>N OR K<1 THEN GOTO 10
30 DIM A(N),C(K):FOR I=1TO K:C(I)=I:NEXT
60 P=0:FOR I=1 TO K:IF C(I)=N-K+I THEN P=P+1:NEXT I ELSE NEXT I
80 IF P=K THEN FOR I=1 TO K:PRINT C(I);:NEXT I:END 'WW
90 FOR J=1 TO K:PRINT C(J);:NEXT J:PRINT
100 FOR J=K TO 1 STEP -1
110 IF C(J)=N-K+J THEN NEXT J:GOTO 60 ELSE C(J)=C(J)+1:IF J+1>K THEN GOTO 60 ELSE FOR I=J+1 TO K:C(I)=C(I-1)+1:NEXT I:GOTO 60
